!TCL=3000, Copyright	(C) 1997 Helios Software Solutions
!TITLE=Control Characters
!SORT=N

!TEXT=SOH	(Start of Heading)

!
!TEXT=STX	(Start of Text)

!
!TEXT=ETX	(End of Text)

!
!TEXT=EOT	(End of Transmission

!
!TEXT=ENQ	(Enquire)

!
!TEXT=ACK	(Acknowledge)

!
!TEXT=BEL	(Bell)

!
!TEXT=BS	(Backspace)

!
!TEXT=HT	(Horizontal Tab)
	
!
!TEXT=VT	(Vertical Tab)

!
!TEXT=FF	(Form Feed)

!
!TEXT=SO	(Shift Out)

!
!TEXT=SI	(Shift In)

!
!TEXT=DLE	(Data Link Escape)

!
!TEXT=DC1	(Device Control 1/X-On)

!
!TEXT=DC2	(Device Control 2)

!
!TEXT=DC3	(Device Control 3/X-off)

!
!TEXT=DC4	(Device Control 4)

!
!TEXT=NAK	(Negative Acknowledgement)

!
!TEXT=SYN	(Synchronous Idle)

!
!TEXT=ETB	(End of Transmission Block)

!
!TEXT=CAN	(Cancel)

!
!TEXT=EM	(End of Medium)

!
!TEXT=SUB	(Substitute)

!
!TEXT=ESC	(Escape)

!
!TEXT=FS	(File Separator)

!
!TEXT=GS	(Group Separator)

!
!TEXT=RS	(Record Separator)

!
!TEXT=US	(Unit Separator)

!
